### ISSUE TITLE
RSS invalid mimetype

### ISSUE THREAD

**Issue by joshcangit** [akalenuk/wordsandbuttons#18]
The RSS from the website doesn't work.
`https://wordsandbuttons.online/rss`

My RSS app can't detect it.
```
Not parsing document with invalid RSS/Atom mimetype: null/null
```

But, the file from this repository works instead.
`https://raw.githubusercontent.com/akalenuk/wordsandbuttons/master/pages/rss`

**Comment by akalenuk** [comment]
Thanks! It does have an invalid MIME. And since it doesn't have an extension, I can't simply add a user-defined mimetype for it ¯\_(ツ)_/¯

Bu! I made a duplicate rss.rss file with the correct mimetype, and updated all the RSS links on the site. It should work now. I also updated the updater so keeping two files is not something I'd have to keep in mind in the future.

**Comment by joshcangit** [comment]
Got it, thanks! :+1:
