### ISSUE TITLE
[Question] How did you build your website? Pure html? 

### ISSUE THREAD

**Issue by lovebes** [akalenuk/wordsandbuttons#19]
Your pages have <p> tags that are one-liners so I don't think a page editor was used, and I don't think this shows signs of a JAM stack like Hugo.

Asking because I like how it was written - it looks simple to maintain. And effective, so I wanted to model yours for my blog.

Thanks in advance.

**Comment by akalenuk** [comment]
Yes, it's just HTML. With a bit of CSS and a lot of hand-written vanilla JavaScript. Moreover, all the pages are self-contained so there are no shared artifacts, no common styles or code. Even more, there are no third-party dependencies.

I was going to see how far could I go this way, since obviously at some point handling tons of copy-pasting should have become unmanageable. But apparently 50+ interactive pages is still the manageable size to go on. 

But I do use Python scripts for batch work. For instance, when I want to change something in a footer for all the pages, I don't do that by hand, I write a one-time script. This way I can tune every page to look exactly as I want it to, and I do have control over common pieces of HTML and CSS too.
